# Header
menu:
#  Home: /
#  Archives: /archives
#  About: /about/index.html
 Blog: /
 Autor: /autor
 Impressum: /impressum
 Datenschutz: /datenschutz
rss: 
github: https://github.com/Baitando

# Content
excerpt_link: Weiterlesen
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
#- tagcloud
#- links

# Links
links: 
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
